"""Initial database setup

Revision ID: f29a57c5e6b6
Revises: 
Create Date: 2025-12-11 18:25:55.046810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f29a57c5e6b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('news_user_id_fkey'), 'news', type_='foreignkey')
    op.create_foreign_key(None, 'news', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('residents_user_id_fkey'), 'residents', type_='foreignkey')
    op.create_foreign_key(None, 'residents', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('residents_to_trainings_resident_id_fkey'), 'residents_to_trainings', type_='foreignkey')
    op.drop_constraint(op.f('residents_to_trainings_training_session_id_fkey'), 'residents_to_trainings', type_='foreignkey')
    op.create_foreign_key(None, 'residents_to_trainings', 'training_sessions', ['training_session_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'residents_to_trainings', 'residents', ['resident_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('training_sessions_training_type_id_fkey'), 'training_sessions', type_='foreignkey')
    op.drop_constraint(op.f('training_sessions_coach_id_fkey'), 'training_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'training_sessions', 'coaches', ['coach_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'training_sessions', 'training_types', ['training_type_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training_sessions', type_='foreignkey')
    op.drop_constraint(None, 'training_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('training_sessions_coach_id_fkey'), 'training_sessions', 'coaches', ['coach_id'], ['id'])
    op.create_foreign_key(op.f('training_sessions_training_type_id_fkey'), 'training_sessions', 'training_types', ['training_type_id'], ['id'])
    op.drop_constraint(None, 'residents_to_trainings', type_='foreignkey')
    op.drop_constraint(None, 'residents_to_trainings', type_='foreignkey')
    op.create_foreign_key(op.f('residents_to_trainings_training_session_id_fkey'), 'residents_to_trainings', 'training_sessions', ['training_session_id'], ['id'])
    op.create_foreign_key(op.f('residents_to_trainings_resident_id_fkey'), 'residents_to_trainings', 'residents', ['resident_id'], ['id'])
    op.drop_constraint(None, 'residents', type_='foreignkey')
    op.create_foreign_key(op.f('residents_user_id_fkey'), 'residents', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.create_foreign_key(op.f('news_user_id_fkey'), 'news', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
